### ISSUE TITLE
个别抖音直播间开播时无法检测到

### ISSUE THREAD

**Issue by mortgoupil** [hua0512/stream-rec#105]
使用中发现一个主播的直播间始终无法检测到开播，怀疑可能是因为抖音id带有下划线导致的，烦请查看能否修复？（同时使用的其他项目可以正常检测到该主播开播并下载）

直播链接：https://live.douyin.com/two_dy

**Comment by hua0512** [comment]
麻烦使用最新latest重新测试一下哈

**Comment by mortgoupil** [comment]
> 麻烦使用最新latest重新测试一下哈

可以正常识别啦，谢谢大佬
