### ISSUE TITLE
支持IPV6访问

### ISSUE THREAD

**Issue by Xalelezhang** [hua0512/stream-rec#115]
支持IPV6访问

**Comment by hua0512** [comment]
支持的
![image](https://github.com/user-attachments/assets/7e5948e7-2b76-4fbb-831f-8041470c9c98)

![image](https://github.com/user-attachments/assets/d6dba8a6-b7fa-41c6-9be5-1b0669f76322)

**Comment by hua0512** [comment]
前端参考
![image](https://github.com/user-attachments/assets/43ec71d6-63dd-4c56-a31a-a8a608707f02)
