### ISSUE TITLE
Feature Request: Add support for streamlink-ttvlol

### ISSUE THREAD

**Issue by revunix** [hua0512/stream-rec#149]
Hello,

First of all, thank you for your great work on this project!

I would like to request a feature or guidance on how to integrate [streamlink-ttvlol](https://github.com/2bc4/streamlink-ttvlol/) with the Docker container of this project. It would be very useful for bypassing ads on Twitch streams, and I believe other users might find it helpful as well.

Could you consider adding support for streamlink-ttvlol or provide instructions on how to add it to the Docker container manually?

Thanks in advance for your consideration!

**Comment by hua0512** [comment]
Hi, what´s the difference of using this plugin and the arg `--twitch-disable-ads`?

**Comment by revunix** [comment]
Hi,

The `--twitch-disable-ads` argument is not entirely reliable, as it still encounters some issues. On the other hand, the `streamlink-ttvlol` plugin uses proxy servers located in countries where Twitch doesn't serve ads. I've been using it for a long time and have never experienced ads in the recordings.

Hope this helps, https://github.com/2bc4/streamlink-ttvlol/?tab=readme-ov-file#known-compatible-public-proxy-servers !

**Comment by hua0512** [comment]
Looks good, I will try to integrate it and possibly add this feature in the next release. Btw, these servers are compatibles with the `HTTP_PROXY`?

**Comment by revunix** [comment]
No, the servers don’t work with HTTP_PROXY. They fetch the playlist and generate their own .m3u8 file. The only workaround that comes to mind is using GlueTUN with a VPN on the Docker container, which might solve my problem temporarily.

However, if I use the auth-token, wouldn’t subs be taken into account? In that case, I shouldn’t get ads on channels I’m subscribed to, right?

**Comment by hua0512** [comment]
That's rigth. Using a twitch turbo auth-token or subscribing to the channel should avoid the ads.

**Comment by revunix** [comment]
Thanks for the information. Unfortunately, I don’t have Turbo, but I subscribe through Turkey for 6 months at under $2, which is cheaper than Turbo. I would really appreciate it if you could add this plugin.

**Comment by hua0512** [comment]
Hi, a commit with the requested feature is pushed to the latest branch. Can u confirm that proxy works correctly? 
Thanks!

**Comment by revunix** [comment]
Looks good!

```bash
stream-rec           | 10-01 23:07:47.832 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [plugins.twitch][info] streamlink-ttvlol 6.8.2-20240705 (6.10.0)
stream-rec           | 10-01 23:07:47.832 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlink-ttvlol/issues
stream-rec           | 10-01 23:07:47.833 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [cli][info] Found matching plugin twitch for URL https://www.twitch.tv/papaplatte
stream-rec           | 10-01 23:07:47.833 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [plugins.twitch][info] Using playlist proxy 'https://as.luminous.dev'
stream-rec           | 10-01 23:07:49.128 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
stream-rec           | 10-01 23:07:49.128 [DefaultDispatcher-worker-4] INFO  Streamlink - Papaplatte [cli][info] Opening stream: 1080p60 (hls)
```

**Comment by hua0512** [comment]
> Small question, would it be possible to record PART files into another folder, and when they are finished, into a folder with finished files?! I watch my recordings with Plex. And then it keeps deleting files when they are finished and swapping them. And a possibility to change the username would also be cool.

Hi, the first option is possible by using a [callback](https://github.com/stream-rec/stream-rec/blob/main/docs/Configuration.md#41-streamer-callbacks) to move files to another directory. Changing the username is not possible at the moment, but you can grab the database file, pass it to a database editor, and change the username. An account system is planned to be added in a future version.
