### ISSUE TITLE
docker 版的一些问题

### ISSUE THREAD

**Issue by gxusb** [hua0512/stream-rec#50]
- 时区不是中国时区
- docker-compose.yml 文件没有映射 rclone 的配置目录，每次使用`docker-compose up -d`启动时 rclone 配置都会丢失

**Comment by hua0512** [comment]
1. 嗨，因为我本人在国外所以没注意到哈。 等下有空push一下。
2. 解决这个很简单，把rclone conf放到录播文件夹下就好了，后处理参数带上。
![image](https://github.com/hua0512/stream-rec/assets/61939061/3771b9f1-013f-41da-85fa-ee875f13f964)
