### ISSUE TITLE
更新后处理模版会清除录播文件

### ISSUE THREAD

**Issue by gxusb** [hua0512/stream-rec#56]
会清除正在录播的文件

**Comment by hua0512** [comment]
![image](https://github.com/hua0512/stream-rec/assets/61939061/11d4eda0-44eb-43d0-8eb9-42c194705b67)
是这个意思吗

**Comment by gxusb** [comment]
立即生效，清除文件

**Comment by hua0512** [comment]
> 立即生效，清除文件

这逻辑上是对的。 我当时想着是你都更改设置了那肯定就不要旧的了。 而且某些视频格式中断后是无法播放的（MP4），所以只能删掉。 有什么好建议吗

**Comment by gxusb** [comment]
没有结束录制机制吗，ffmpeg 可以中断的

> > 立即生效，清除文件
> 
> 这逻辑上是对的。 我当时想着是你都更改设置了那肯定就不要旧的了。 而且某些视频格式中断后是无法播放的（MP4），所以只能删掉。 有什么好建议吗

**Comment by hua0512** [comment]
> 没有结束录制机制吗，ffmpeg 可以中断的
> 
> > > 立即生效，清除文件
> > 
> > 
> > 这逻辑上是对的。 我当时想着是你都更改设置了那肯定就不要旧的了。 而且某些视频格式中断后是无法播放的（MP4），所以只能删掉。 有什么好建议吗

ffmpeg中断是输入q对吗，MP4输入q的情况下还能播放吗？

**Comment by gxusb** [comment]
能

> > 没有结束录制机制吗，ffmpeg 可以中断的
> > > > 立即生效，清除文件
> > > 
> > > 
> > > 这逻辑上是对的。 我当时想着是你都更改设置了那肯定就不要旧的了。 而且某些视频格式中断后是无法播放的（MP4），所以只能删掉。 有什么好建议吗
> 
> ffmpeg中断是输入q对吗，MP4输入q的情况下还能播放吗？

**Comment by hua0512** [comment]
> 能
> 
> > > 没有结束录制机制吗，ffmpeg 可以中断的
> > > > > 立即生效，清除文件
> > > > 
> > > > 
> > > > 这逻辑上是对的。 我当时想着是你都更改设置了那肯定就不要旧的了。 而且某些视频格式中断后是无法播放的（MP4），所以只能删掉。 有什么好建议吗
> > 
> > 
> > ffmpeg中断是输入q对吗，MP4输入q的情况下还能播放吗？

🆗，那我明天改一下。 更新配置后将取消当前录制，大于`最小分段大小`的将会保留。
比较头疼的是Alpine linux的streamlink包炸了#54， 打算临时切换py镜像来安装，就是docker镜像大小会变大一点。

**Comment by hua0512** [comment]
麻烦测试一下最新版本哈

**Comment by gxusb** [comment]
<img width="1367" alt="image" src="https://github.com/hua0512/stream-rec/assets/105532932/891b1b1a-5efd-4cd4-b78b-1a8345ba905d">

**Comment by hua0512** [comment]
> <img alt="image" width="1367" src="https://private-user-images.githubusercontent.com/105532932/326308058-891b1b1a-5efd-4cd4-b78b-1a8345ba905d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjUxMDcsIm5iZiI6MTcxNDU2NDgwNywicGF0aCI6Ii8xMDU1MzI5MzIvMzI2MzA4MDU4LTg5MWIxYjFhLTVlZmQtNGNkNC1iNzhiLTFhODM0NWJhOTA1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMjAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmUyNDUxZTA4MjdiNjI5YjdkZjc2ZmM4OGZhODMyN2I1YWI5YmRjYzQ3ZjQzNzcyNzk0MWEyY2RiYjEyNGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C_Usn3A02qyno9xlBKmC8Kz47tEUQnctgI3aJ8BkIao">

浏览器系统的时区是不是跟容器的不一样

**Comment by gxusb** [comment]
> 浏览器系统的时区是不是跟容器的不一样

webUI那个容器可以设置时区吗

**Comment by hua0512** [comment]
> > 浏览器系统的时区是不是跟容器的不一样
> 
> webUI那个容器可以设置时区吗
> 
> 

可以，一样的方法
